
USE gamevault_db;

-- EMPRESAS
INSERT INTO empresa (nombre, fundacion, historia, img) VALUES
('Nintendo', '1889', 'Empezo como una empresa de juguetes que se volvio una empresa de videojuegos en los 70s, su impacto de hizo dramaticamente grandes empezando en los 80s', 'https://upload.wikimedia.org/wikipedia/commons/9/95/Nintendo_Logo_2017.png'),
('Sony', '1946', 'Se unio a las consolas despues de que Nintendo rompio su contrato, ya que obtuvieron informacion util de ello, desde entonces ha sido un gran jugador en la industria con su marca PlayStation', ''),
('Microsoft', '1975', 'Debido a que percibio a Sony como una amenaza debido al exito de la PlayStation 2 y su capacidad de correr linux, se unio a la industria del videojuego con su marca Xbox en 2001', '');

-- VIDEOJUEGOS
INSERT INTO videojuegos (nombre, descripcion, rating, plat, genero, precio, img) VALUES
('Little Big Planet', 'Un juego de plataformas con elementos de creatividad y fantacia, crea y comparte personajes y niveles', '8/10', 'PlayStation Portable, PlayStation 3', 'Plataformas', 600, 'https://m.media-amazon.com/images/M/MV5BNmFiNGYxMTQtMzE5Mi00MDZmLWFiZDgtNDNmMGViNDY1MzMwXkEyXkFqcGc@._V1_.jpg'),
('Halo 3', 'El final de la trilogia de Bunjie, termina la batalla contra el covenant en este juego de tiros y accion', '9/10', 'Xbox 360', 'Disparos, Accion', 1000, 'https://m.media-amazon.com/images/M/MV5BZmQyNTVkOGMtMzZhNi00ZDRjLWJkNzctZTYxMTMxYTYzZjVmXkEyXkFqcGc@._V1_.jpg'),
('Super Mario Galaxy', 'Derrota a bowser y rescata a Peach y la galaxia entera en esta divertida aventura de Mario', '9/10', 'Nintendo Wii', 'Plataformas', 600, 'https://m.media-amazon.com/images/M/MV5BOWRlNDkyYTctMmE5Yi00Zjk1LWJmNzAtMDg5YWFjMTEzNDFjXkEyXkFqcGc@._V1_.jpg'),
('Ratchet & Clank', 'Unete a ratchet y clank a salvar su sistema solar', '8/10', 'PlayStation 2, PlayStation 3, PlayStation Vita', 'Disparos en tercera persona', 400, 'https://m.media-amazon.com/images/M/MV5BNDBkZDBkMzYtYmQ3Zi00ZTQ3LTk1NzAtMWExYzkyZTFmNjg1XkEyXkFqcGc@._V1_.jpg'),
('Gears of War', 'Defiende a la tierra de invasores que amenazan la raza humana', '8/10', 'Xbox 360, Xbox One, Xbox Series X/S', 'Disparos en tercera persona', 800, 'https://m.media-amazon.com/images/M/MV5BYzEzMDI4ODEtYzRmMy00NGIwLWExM2ItMzY0YzRjMmVkMDg3XkEyXkFqcGc@._V1_.jpg'),
('Jak & Daxter', 'Descubre el misterio de los precursores de energia y la energia oscura', '9/10', 'PlayStation 2, PlayStation 3', 'Plataformas', 400, 'https://m.media-amazon.com/images/M/MV5BNWI1ZDFlZTAtYTlhMy00MzIyLWFmMDktYThjM2IwZWE2NWE0XkEyXkFqcGc@._V1_.jpg'),
('Crash Bandicoot', 'Ayuda a crash a rescatar a su novia Tawna de la garras de cortex', '8/10', 'PlayStation, PlayStation 3, PlayStation Portable', 'Plataformas', 300, 'https://m.media-amazon.com/images/M/MV5BNWIwZTFkMmEtNDU3ZS00NGM4LTg2ZDMtOTE4MDc2YjM3OTI1XkEyXkFqcGc@._V1_.jpg'),
('Kirby and the Amazing Mirrot', 'El mundo del espejo esta siendo invadido por una sombra y causando caos', '7/10', 'GameBoy Advance', 'Exploracion', 400, 'https://m.media-amazon.com/images/M/MV5BYWQ1NGUyYWYtMGM1MC00Yjk2LWE5NGMtOGExYjQwODgyMmIwXkEyXkFqcGc@._V1_.jpg'),
('Forza Horizons 5', 'Compite en carreras y haz un nombre para ti', '7/10', 'Xbox One, Xbox Series X/S', 'Carreras', 800, 'https://m.media-amazon.com/images/M/MV5BZDA5M2M4YmEtMDMxYy00ZTk5LWIwNGYtNDRmMjI2OTA3OGNiXkEyXkFqcGc@._V1_.jpg'),
('God of War', 'Después de 10 años de servidumbre a los dioses, a Kratos se le encarga la tarea de matar a Ares, el Dios de la Guerra', '8/10', 'PlayStation 2, PlayStation 3', 'Slasher', 400, 'https://m.media-amazon.com/images/M/MV5BMDkxMzExYjAtZmQwMC00MmQzLWE1M2QtMGEwY2M1N2I0NDIwXkEyXkFqcGc@._V1_.jpg'),
('Sonic Unleashed', 'Restora el planeta despues de que el doctor Eggman resucita y usa a Dark Gaia, juega en las faches de noche y dia', '7/10', 'PlayStation 3, Xbox 360, Xbox One, Xbox Series X/S', 'Plataformas', 500, 'https://m.media-amazon.com/images/M/MV5BYTY1MGM4ZTAtMGE5OS00YmFlLWIyNWQtYzFjOGJkMDhlZTIxXkEyXkFqcGc@._V1_.jpg'),
('Celeste', 'Escala una montaña para alejarte de tus problemas y descubrete a ti mismo', '9/10', 'PlayStation 4, Xbox One, Xbox Series X/S, Nintendo Switch', 'Plataformas', 600, 'https://m.media-amazon.com/images/M/MV5BODA3YzM4YzUtMWRlNS00YjRhLTgyMmYtYTQxYjA4YjM0NmE2XkEyXkFqcGc@._V1_.jpg'),
('Castle Crashers', 'Deten al rey oscuro a conquistar el reino y secuestrar las princesas junto a 3 otros acompañantes', 'Xbox 360, PlayStation 3', 'Beat them up', 500, 'https://m.media-amazon.com/images/M/MV5BZWEwZDNiOTAtZDg1Ny00MjcwLWE3MTAtZTI2NDdhN2Q1MGM1XkEyXkFqcGc@._V1_.jpg'),
('The Legend of Zelda: Breath of the Wild', 'Despues de una centena, Link despierta una vez mas a derrotar el mal en Hyrule', 'Wii U, Nintendo Switch, Nintendo Switch 2', 'Exploracion', 1200, 'https://m.media-amazon.com/images/M/MV5BNjI0NTEwZDYtZDhlOC00MGM2LWFlNGItY2U2ZWRkMzk2ODI0XkEyXkFqcGc@._V1_.jpg'),
('Viva Piñata', 'Haz fiestas e interactua con personajes divertidos en esta tierra loca', 'Xbox 360, Xbox One, Xbox Series X/S', 'Exploracion', 600, 'https://m.media-amazon.com/images/M/MV5BOGRlYzM0MzEtZWE0Ny00NmM0LWI4OWItZmZkN2M5YjBlYjdmXkEyXkFqcGc@._V1_.jpg'),
('Metal Gear Solid 3: Sneak Eater', 'I give my life, not for honor, but for you, I\'m still in a dream, sneak eater', 'PlayStation 2', 'Sigilo', 500, 'https://m.media-amazon.com/images/M/MV5BMjBiN2JkMzYtZjdmNC00ZTcyLWIxZjItNGU1ZDNiODI3NGE5XkEyXkFqcGc@._V1_.jpg'),
('Mario Kart 8 Deluxe', 'Una version mejorada de Mario Kart 8 con contenido nuevo para mas diversion entre amigos', 'Nintendo Switch, Nintendo Switch 2', 'Carreras', 1200, 'https://m.media-amazon.com/images/M/MV5BZDg2ODExM2QtNTA1Ny00ODI2LWI4NjMtMDdmZGFjMzczYjEwXkEyXkFqcGc@._V1_.jpg'),
('Pokemon Emerald', 'Una version mejorada de safiro y rubi, contiene nuevo contenido', 'GameBoy Advance', 'RPG', 600, 'https://m.media-amazon.com/images/M/MV5BMmU5YmM4MGQtODE5MS00NmYwLWEwNDItY2Q2ZmJjYzFhOTFhXkEyXkFqcGc@._V1_.jpg'),
('Street Fighter', 'Disfruta de una variedad de modos de juegos que prueban tu habilidad y fuerza contra los maestros de las artes marciales', 'Xbox One, Xbox Series X/S, PlayStation 4, PlayStation 5, Nintendo Switch 2', 'Peleas', 600, 'https://m.media-amazon.com/images/M/MV5BMTY4OTMyNDEtM2RlZi00MWI1LWE2ZDQtMDIwMDAxMDgyNjk2XkEyXkFqcGc@._V1_.jpg'),
('Civilation 6', 'Escoje entre diferentes naciones a lo largo del tiempo y crece un imperio para alcanzar la victoria', 'Xbox One, Xbox Series X/S, PlayStation 4, PlayStation 5, Nintendo Switch, Nintendo Switch 2', 'Estrategia en tiempo real', 600, 'https://m.media-amazon.com/images/M/MV5BMGYxMjQwYTMtY2EyOC00Mzk0LTg2MWMtMjg3ODVhMWNjOGYyXkEyXkFqcGc@._V1_.jpg'),
('Alien Isolation', 'Escondete y escapa de la nave infestada por aliens que contiene informacion sobre la desaparicion de la madre de tu madre', 'Xbox 360, Xbox One, Xbox Series X/S, PlayStation 3, PlayStation 4, PlayStation 5, Nintendo Switch, Nintendo Switch 2', 'Terror', 800, 'https://m.media-amazon.com/images/M/MV5BZTMyNzJlYmUtYTRlNi00ZDdhLWE5MGUtNjg5MzMyZWNiODA2XkEyXkFqcGc@._V1_.jpg');
