version: "3.9"

volumes:
  gamevault_dbdata:

services:

  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: gamesUsers
      DATABASE_PASSWORD: 1234567
      DATABASE_NAME: gamevault_db
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  db:
    image: mysql:8
    volumes:
      - gamevault_dbdata:/var/lib/mysql
    environment:
      MYSQL_USER: gamesUsers
      MYSQL_PASSWORD: 1234567
      MYSQL_DATABASE: gamevault_db
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3312:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
